// <auto-generated />
using EFT_Hud.DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFT_Hud.DAL.Migrations
{
    [DbContext(typeof(EftHudDbContext))]
    [Migration("20200213021055_Adding_Locations")]
    partial class Adding_Locations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.ItemObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<bool>("FindInRaid")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnName("Item_Id")
                        .HasColumnType("int");

                    b.Property<int>("QuestId")
                        .HasColumnName("Quest_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("QuestId");

                    b.ToTable("ItemObjective");
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shoreline"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Woods"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Interchange"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Customs"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Factory"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Reserve"
                        },
                        new
                        {
                            Id = 7,
                            Name = "The Lab"
                        });
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.LocationToQuest", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "QuestId");

                    b.HasIndex("QuestId");

                    b.ToTable("LocationToQuest");
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Merchant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconName = "Prapor_Portrait.png",
                            Name = "Prapor"
                        },
                        new
                        {
                            Id = 2,
                            IconName = "Therapist_Portrait.png",
                            Name = "Therapist"
                        },
                        new
                        {
                            Id = 3,
                            IconName = "Skier_Portrait.png",
                            Name = "Skier"
                        },
                        new
                        {
                            Id = 4,
                            IconName = "Peacekeeper_Portrait.png",
                            Name = "Peacekeeper"
                        },
                        new
                        {
                            Id = 5,
                            IconName = "Mechanic_Portrait.png",
                            Name = "Mechanic"
                        },
                        new
                        {
                            Id = 6,
                            IconName = "Ragman_Portrait.png",
                            Name = "Ragman"
                        },
                        new
                        {
                            Id = 7,
                            IconName = "Jaeger_Portrait.png",
                            Name = "Jaeger"
                        },
                        new
                        {
                            Id = 8,
                            IconName = "Fence_Portrait.png",
                            Name = "Fence"
                        });
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestId")
                        .HasColumnName("Quest_Id")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.ToTable("Objective");
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<int>("MerchantId")
                        .HasColumnName("Merchant_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("Quest");
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestId")
                        .HasColumnName("Quest_Id")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.ToTable("Reward");
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.ItemObjective", b =>
                {
                    b.HasOne("EFT_Hud.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFT_Hud.DAL.Entities.Quest", "Quest")
                        .WithMany("ItemObjectives")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.LocationToQuest", b =>
                {
                    b.HasOne("EFT_Hud.DAL.Entities.Quest", "Quest")
                        .WithMany("Locations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFT_Hud.DAL.Entities.Location", "Location")
                        .WithMany("Quests")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Objective", b =>
                {
                    b.HasOne("EFT_Hud.DAL.Entities.Quest", "Quest")
                        .WithMany("Objectives")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Quest", b =>
                {
                    b.HasOne("EFT_Hud.DAL.Entities.Merchant", "Merchant")
                        .WithMany("Quests")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Reward", b =>
                {
                    b.HasOne("EFT_Hud.DAL.Entities.Quest", "Quest")
                        .WithMany("Rewards")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
