// <auto-generated />
using System;
using EFT_Hud.DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFT_Hud.DAL.Migrations
{
    [DbContext(typeof(EftHudDbContext))]
    partial class EftHudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("IconName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ShortName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Old firesteel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Antique axe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Battered antique Book"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FireKlean gun lube"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Golden rooster"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Silver Badge"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Deadlyslob's beard oil"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Golden 1GPhone"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jar of DevilDog mayo"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Can of sprats"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Fake mustache"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Kotton beanie"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Secure container Kappa"
                        },
                        new
                        {
                            Id = 14,
                            Name = "MP-133 pump-action shotguns"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Roubles"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Euro"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Dollars"
                        },
                        new
                        {
                            Id = 18,
                            Name = "PM 9x18PM pistol"
                        },
                        new
                        {
                            Id = 19,
                            Name = "90-93 9x18PM Magazine, for 8 PM rounds"
                        },
                        new
                        {
                            Id = 20,
                            Name = "bronze pocket watch"
                        },
                        new
                        {
                            Id = 21,
                            Name = "TT pistol 7.62x25 TT"
                        },
                        new
                        {
                            Id = 22,
                            Name = "TT-105 7.62x25 TT Magazine"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Kalashnikov AKS-74U 5.45x39"
                        },
                        new
                        {
                            Id = 24,
                            Name = "6L20 30-round 5.45x39 magazine for AK-74 and compatible weapons"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Saiga 12ga ver. 10 12/76 shotgun"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Sb.5 5-round 12/76 magazine for SOK-12 and compatible weapons"
                        },
                        new
                        {
                            Id = 27,
                            Name = "RGD-5 hand grenade"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Marker 2000"
                        },
                        new
                        {
                            Id = 29,
                            Name = "secure folder 0031"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Key ZB-014"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Portable cabin key of customs Factory zone"
                        },
                        new
                        {
                            Id = 32,
                            Name = "60-round mags for AK"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Sealed letter"
                        });
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shoreline"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Woods"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Interchange"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Customs"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Factory"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Reserve"
                        },
                        new
                        {
                            Id = 7,
                            Name = "The Lab"
                        });
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("IconName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Merchant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconName = "Prapor_Portrait.png",
                            Name = "Prapor"
                        },
                        new
                        {
                            Id = 2,
                            IconName = "Therapist_Portrait.png",
                            Name = "Therapist"
                        },
                        new
                        {
                            Id = 3,
                            IconName = "Skier_Portrait.png",
                            Name = "Skier"
                        },
                        new
                        {
                            Id = 4,
                            IconName = "Peacekeeper_Portrait.png",
                            Name = "Peacekeeper"
                        },
                        new
                        {
                            Id = 5,
                            IconName = "Mechanic_Portrait.png",
                            Name = "Mechanic"
                        },
                        new
                        {
                            Id = 6,
                            IconName = "Ragman_Portrait.png",
                            Name = "Ragman"
                        },
                        new
                        {
                            Id = 7,
                            IconName = "Jaeger_Portrait.png",
                            Name = "Jaeger"
                        },
                        new
                        {
                            Id = 8,
                            IconName = "Fence_Portrait.png",
                            Name = "Fence"
                        });
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("CountDone")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Done")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<bool>("Optional")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UsingItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.HasIndex("QuestId");

                    b.HasIndex("UsingItemId");

                    b.ToTable("Objective");

                    b.HasData(
                        new
                        {
                            Id = 25,
                            Count = 5,
                            CountDone = 0,
                            Description = "Scav",
                            Done = false,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 1,
                            Type = 10
                        },
                        new
                        {
                            Id = 26,
                            Count = 2,
                            CountDone = 0,
                            Done = false,
                            ItemId = 14,
                            Optional = false,
                            QuestId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 20,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 28,
                            Count = 0,
                            CountDone = 0,
                            Description = "Find the key to the tank truck",
                            Done = false,
                            LocationId = 4,
                            Optional = true,
                            QuestId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 29,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 20,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            Count = 15,
                            CountDone = 0,
                            Description = "Scav",
                            Done = false,
                            LocationId = 2,
                            Optional = false,
                            QuestId = 3,
                            Type = 10
                        },
                        new
                        {
                            Id = 31,
                            Count = 1,
                            CountDone = 0,
                            Description = "secure case in the Tarcone Director's Office",
                            Done = false,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = 32,
                            Count = 0,
                            CountDone = 0,
                            Description = "swing room, on 2nd",
                            Done = false,
                            LocationId = 5,
                            Optional = false,
                            QuestId = 4,
                            Type = 9
                        },
                        new
                        {
                            Id = 33,
                            Count = 0,
                            CountDone = 0,
                            Done = false,
                            LocationId = 5,
                            Optional = false,
                            QuestId = 4,
                            Type = 7
                        },
                        new
                        {
                            Id = 34,
                            Count = 0,
                            CountDone = 0,
                            Description = "fuel tank №1",
                            Done = false,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 5,
                            Type = 8,
                            UsingItemId = 28
                        },
                        new
                        {
                            Id = 35,
                            Count = 0,
                            CountDone = 0,
                            Description = "fuel tank №2",
                            Done = false,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 5,
                            Type = 8,
                            UsingItemId = 28
                        },
                        new
                        {
                            Id = 36,
                            Count = 0,
                            CountDone = 0,
                            Description = "fuel tank №3",
                            Done = false,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 5,
                            Type = 8,
                            UsingItemId = 28
                        },
                        new
                        {
                            Id = 37,
                            Count = 0,
                            CountDone = 0,
                            Description = "fuel tank №4",
                            Done = false,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 5,
                            Type = 8,
                            UsingItemId = 28
                        },
                        new
                        {
                            Id = 38,
                            Count = 0,
                            CountDone = 0,
                            Done = false,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 5,
                            Type = 7
                        },
                        new
                        {
                            Id = 39,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 29,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 6,
                            Type = 2
                        },
                        new
                        {
                            Id = 40,
                            Count = 1,
                            CountDone = 0,
                            Description = "Gain access to the closed room in offices",
                            Done = false,
                            LocationId = 5,
                            Optional = true,
                            QuestId = 6,
                            Type = 5
                        },
                        new
                        {
                            Id = 41,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 31,
                            LocationId = 5,
                            Optional = true,
                            QuestId = 6,
                            Type = 2
                        },
                        new
                        {
                            Id = 42,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 29,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 43,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 6,
                            Type = 7
                        },
                        new
                        {
                            Id = 44,
                            Count = 6,
                            CountDone = 0,
                            Done = false,
                            ItemId = 32,
                            Optional = false,
                            QuestId = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = 45,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 30,
                            LocationId = 4,
                            Optional = false,
                            QuestId = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = 46,
                            Count = 1,
                            CountDone = 0,
                            Description = "Locate the right bunker",
                            Done = false,
                            LocationId = 2,
                            Optional = false,
                            QuestId = 7,
                            Type = 5
                        },
                        new
                        {
                            Id = 47,
                            Count = 6,
                            CountDone = 0,
                            Done = false,
                            ItemId = 32,
                            Optional = false,
                            QuestId = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 48,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 33,
                            LocationId = 5,
                            Optional = false,
                            QuestId = 8,
                            Type = 2
                        },
                        new
                        {
                            Id = 49,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            LocationId = 5,
                            Optional = false,
                            QuestId = 8,
                            Type = 7
                        },
                        new
                        {
                            Id = 50,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 33,
                            Optional = false,
                            QuestId = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 1,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 1,
                            Optional = false,
                            QuestId = 24,
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 2,
                            Optional = false,
                            QuestId = 24,
                            Type = 3
                        },
                        new
                        {
                            Id = 3,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 3,
                            Optional = false,
                            QuestId = 24,
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 4,
                            Optional = false,
                            QuestId = 24,
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 5,
                            Optional = false,
                            QuestId = 24,
                            Type = 3
                        },
                        new
                        {
                            Id = 6,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 6,
                            Optional = false,
                            QuestId = 24,
                            Type = 3
                        },
                        new
                        {
                            Id = 7,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 7,
                            Optional = false,
                            QuestId = 24,
                            Type = 3
                        },
                        new
                        {
                            Id = 8,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 8,
                            Optional = false,
                            QuestId = 24,
                            Type = 3
                        },
                        new
                        {
                            Id = 9,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 9,
                            Optional = false,
                            QuestId = 24,
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 10,
                            Optional = false,
                            QuestId = 24,
                            Type = 3
                        },
                        new
                        {
                            Id = 11,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 11,
                            Optional = false,
                            QuestId = 24,
                            Type = 3
                        },
                        new
                        {
                            Id = 12,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 12,
                            Optional = false,
                            QuestId = 24,
                            Type = 3
                        },
                        new
                        {
                            Id = 13,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 1,
                            Optional = false,
                            QuestId = 24,
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 2,
                            Optional = false,
                            QuestId = 24,
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 3,
                            Optional = false,
                            QuestId = 24,
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 4,
                            Optional = false,
                            QuestId = 24,
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 5,
                            Optional = false,
                            QuestId = 24,
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 6,
                            Optional = false,
                            QuestId = 24,
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 7,
                            Optional = false,
                            QuestId = 24,
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 8,
                            Optional = false,
                            QuestId = 24,
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 9,
                            Optional = false,
                            QuestId = 24,
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 10,
                            Optional = false,
                            QuestId = 24,
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 11,
                            Optional = false,
                            QuestId = 24,
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            Count = 1,
                            CountDone = 0,
                            Done = false,
                            ItemId = 12,
                            Optional = false,
                            QuestId = 24,
                            Type = 1
                        });
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("Quest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MerchantId = 1,
                            Name = "Debiut",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            MerchantId = 1,
                            Name = "Checking",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            MerchantId = 1,
                            Name = "Shootout picnic",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            MerchantId = 1,
                            Name = "Delivery from the past",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            MerchantId = 1,
                            Name = "BP Depot",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            MerchantId = 1,
                            Name = "Bad rep evidence",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            MerchantId = 1,
                            Name = "Ice cream cones",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            MerchantId = 1,
                            Name = "Postman part - part 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            MerchantId = 1,
                            Name = "Shaking up teller",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            MerchantId = 1,
                            Name = "The Punisher - part 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            MerchantId = 1,
                            Name = "The Punisher - part 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            MerchantId = 1,
                            Name = "The Punisher - part 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            MerchantId = 1,
                            Name = "The Punisher - part 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            MerchantId = 1,
                            Name = "The Punisher - part 5",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            MerchantId = 1,
                            Name = "The Punisher - part 6",
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            MerchantId = 1,
                            Name = "Polikhim hobo",
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            MerchantId = 1,
                            Name = "Big customer",
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            MerchantId = 1,
                            Name = "No offence",
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            MerchantId = 1,
                            Name = "Grenadier",
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            MerchantId = 1,
                            Name = "Perfect mediator",
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            MerchantId = 1,
                            Name = "Insomnia",
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            MerchantId = 1,
                            Name = "Test drive - Part 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            MerchantId = 1,
                            Name = "Regulated materials",
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            MerchantId = 2,
                            Name = "Shortage",
                            Status = 0
                        },
                        new
                        {
                            Id = 26,
                            MerchantId = 2,
                            Name = "Sanitary Standards - Part 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 27,
                            MerchantId = 2,
                            Name = "Sanitary Standards - Part 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 28,
                            MerchantId = 2,
                            Name = "Operation Aquarius - Part 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 29,
                            MerchantId = 2,
                            Name = "Operation Aquarius - Part 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 30,
                            MerchantId = 2,
                            Name = "Painkiller",
                            Status = 0
                        },
                        new
                        {
                            Id = 31,
                            MerchantId = 2,
                            Name = "Pharmacist",
                            Status = 0
                        },
                        new
                        {
                            Id = 32,
                            MerchantId = 2,
                            Name = "Supply plans",
                            Status = 0
                        },
                        new
                        {
                            Id = 33,
                            MerchantId = 2,
                            Name = "General wares",
                            Status = 0
                        },
                        new
                        {
                            Id = 34,
                            MerchantId = 2,
                            Name = "Car repair",
                            Status = 0
                        },
                        new
                        {
                            Id = 35,
                            MerchantId = 2,
                            Name = "Health Care Privacy - Part 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 36,
                            MerchantId = 2,
                            Name = "Health Care Privacy - Part 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 37,
                            MerchantId = 2,
                            Name = "Health Care Privacy - Part 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 38,
                            MerchantId = 2,
                            Name = "Health Care Privacy - Part 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 39,
                            MerchantId = 2,
                            Name = "Health Care Privacy - Part 5",
                            Status = 0
                        },
                        new
                        {
                            Id = 40,
                            MerchantId = 2,
                            Name = "Postman Pat - Part 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 41,
                            MerchantId = 2,
                            Name = "Out of curiosity",
                            Status = 0
                        },
                        new
                        {
                            Id = 42,
                            MerchantId = 2,
                            Name = "Trust regain",
                            Status = 0
                        },
                        new
                        {
                            Id = 43,
                            MerchantId = 2,
                            Name = "Hippocratic Vow",
                            Status = 0
                        },
                        new
                        {
                            Id = 44,
                            MerchantId = 2,
                            Name = "Private clinic",
                            Status = 0
                        },
                        new
                        {
                            Id = 45,
                            MerchantId = 2,
                            Name = "Athlete",
                            Status = 0
                        },
                        new
                        {
                            Id = 46,
                            MerchantId = 2,
                            Name = "Decontamination service",
                            Status = 0
                        },
                        new
                        {
                            Id = 47,
                            MerchantId = 2,
                            Name = "An apple a day - keeps the doctor away",
                            Status = 0
                        },
                        new
                        {
                            Id = 24,
                            MerchantId = 8,
                            Name = "Collector",
                            Status = 0
                        });
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("Count")
                        .HasColumnType("double");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("QuestId")
                        .HasColumnName("Quest_Id")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("QuestId");

                    b.ToTable("Reward");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Count = 600.0,
                            QuestId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Count = 0.080000000000000002,
                            QuestId = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            Count = 5000.0,
                            ItemId = 15,
                            QuestId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Count = 1.0,
                            ItemId = 18,
                            QuestId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Count = 1.0,
                            ItemId = 19,
                            QuestId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Unlocks purchase of Kalashnikov AKS-74U 5.45x39 at LL1",
                            QuestId = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Count = 8000.0,
                            QuestId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Count = 0.080000000000000002,
                            QuestId = 2,
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            Count = 4000.0,
                            ItemId = 15,
                            QuestId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Count = 1.0,
                            ItemId = 21,
                            QuestId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Count = 3.0,
                            ItemId = 22,
                            QuestId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Count = 2000.0,
                            QuestId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Count = 0.10000000000000001,
                            QuestId = 3,
                            Type = 3
                        },
                        new
                        {
                            Id = 15,
                            Count = 6000.0,
                            ItemId = 15,
                            QuestId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            Count = 3.0,
                            ItemId = 23,
                            QuestId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            Count = 3.0,
                            ItemId = 24,
                            QuestId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            Count = 4100.0,
                            QuestId = 4,
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            Count = 0.11,
                            QuestId = 4,
                            Type = 3
                        },
                        new
                        {
                            Id = 20,
                            Count = 12000.0,
                            ItemId = 15,
                            QuestId = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            Count = 3.0,
                            ItemId = 25,
                            QuestId = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            Count = 3.0,
                            ItemId = 26,
                            QuestId = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            Description = "Unlocks purchase of 5.45x39 mm PS at LL1",
                            QuestId = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = 24,
                            Count = 2900.0,
                            QuestId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            Count = 0.080000000000000002,
                            QuestId = 5,
                            Type = 3
                        },
                        new
                        {
                            Id = 26,
                            Count = -0.01,
                            QuestId = 5,
                            Type = 9
                        },
                        new
                        {
                            Id = 27,
                            Count = 8000.0,
                            ItemId = 15,
                            QuestId = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            Count = 3.0,
                            ItemId = 27,
                            QuestId = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 1,
                            Count = 1.0,
                            ItemId = 13,
                            QuestId = 24,
                            Type = 0
                        });
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Objective", b =>
                {
                    b.HasOne("EFT_Hud.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("EFT_Hud.DAL.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("EFT_Hud.DAL.Entities.Quest", "Quest")
                        .WithMany("Objectives")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFT_Hud.DAL.Entities.Item", "UsingItem")
                        .WithMany()
                        .HasForeignKey("UsingItemId");
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Quest", b =>
                {
                    b.HasOne("EFT_Hud.DAL.Entities.Merchant", "Merchant")
                        .WithMany("Quests")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFT_Hud.DAL.Entities.Reward", b =>
                {
                    b.HasOne("EFT_Hud.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("EFT_Hud.DAL.Entities.Quest", "Quest")
                        .WithMany("Rewards")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
